/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface CreateCategoryInput { 'name' : string }
export interface CreateOrderInput {
  'customerName' : string,
  'city' : [] | [string],
  'totalAmount' : bigint,
  'contactNumber' : string,
  'items' : Array<OrderItemInput>,
}
export interface CreateProductInput {
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'city' : [] | [string],
  'totalAmount' : bigint,
  'timestamp' : Time,
  'contactNumber' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderItemInput {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type Time = bigint;
export interface UpdateProductInput {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCategory' : ActorMethod<[CreateCategoryInput], bigint>,
  'addProduct' : ActorMethod<[CreateProductInput], bigint>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[CreateOrderInput], bigint>,
  'updateProduct' : ActorMethod<[UpdateProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];